version: '3'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: edufi-mongo
    ports:
    - 8128:27017
    environment:
      - MONGO_INITDB_DATABASE=StudentMarks
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
